sudo: required

services:
  - docker

before_install:
  - docker build -t sam35/docker-react -f Dockerfile.dev .
script:
  # - docker run sam35/docker-react npm run test -- --coverage
  - docker run -e CI=true sam35/docker-react npm run test -- --watchAll=false
  # if we ever get a non zero return code, travis assumes your code is broken

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: Docker-env
  bucket_name: elasticbeanstalk-us-east-1-846502526912
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"