sudo: required

services:
  - docker

before_install:
  - docker build -t sam35/docker-react -f Dockerfile.dev .
script:
  # if we ever get a non zero return code, travis assumes your code is broken
  - docker run sam35/docker-react npm run test -- --coverage