version: '3'

services:
  web:
    # build: .
    build:
    # context is where docker-compose looks for files
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3004:3000
    volumes:
      - /app/node_modules
      - .:/app

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    #overwrite starting command (npm run test intead of npm run test)
    command: ["npm", "run", "test"]
